/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myjavaapplication;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MAXPRO
 */
public class demoinfo extends javax.swing.JFrame {

    /**
     * Creates new form demoinfo
     */
    public demoinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        nameinfo = new javax.swing.JTextField();
        jaddress = new javax.swing.JLabel();
        addressinfo = new javax.swing.JTextField();
        jphoneno = new javax.swing.JLabel();
        phonenoinfo = new javax.swing.JTextField();
        jdepartment = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        cmbDept = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jtitle.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jtitle.setText("Student Infromation");

        jname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jname.setText("Name");

        jaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jaddress.setText("Address");

        jphoneno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jphoneno.setText("Phone No");

        jdepartment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdepartment.setText("Department");

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        cmbDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "ECE", "EEE", "MECH" }));
        cmbDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeptActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnclr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclr.setText("Clear");
        btnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnclr)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jname)
                            .addComponent(jaddress)
                            .addComponent(jphoneno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addressinfo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonenoinfo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDept, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameinfo)))
                    .addComponent(jtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtitle)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jname)
                    .addComponent(nameinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jaddress)
                    .addComponent(addressinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jphoneno)
                    .addComponent(phonenoinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdepartment)
                    .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(jButton2))
                .addGap(42, 42, 42)
                .addComponent(btnclr)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        
        String name = nameinfo.getText().trim();
        String address =addressinfo.getText().trim();
        String phoneno = phonenoinfo.getText().trim();
        String department = cmbDept.getSelectedItem().toString();
       // int id = txtid.getText().charAt(0);
       
        if(name.isEmpty()|| address.isEmpty()|| phoneno.isEmpty() || department.isEmpty() ){
            JOptionPane.showMessageDialog(this,"All fields are required");
                }
        else{
            JOptionPane.showMessageDialog(this, "Infromation Entered");
           // JOptionPane.showMessageDialog(this, "Signup Error!");
           
       }
        try {
          
       Connection con = DBConnection.getConnection();

       String sql = "INSERT INTO  studentdata ( name, address, phoneno, department) VALUES(?,?,?,?)";
       PreparedStatement ps = con.prepareStatement(sql);

// Match the order of the columns defined in the SQL string above
//ps.setInt(1, id);            // id is 1st
       ps.setString(1, name);       // name is 2nd
       ps.setString(2, address);    // address is 3rd
       ps.setString(3, phoneno);    // phoneno is 4th
       ps.setString(4, department); // department is 5th

       ps.executeUpdate();

       JOptionPane.showMessageDialog(this, "Insert Successful!");
      //  new demologin().setVisible(true);
        //this.dispose();
        nameinfo.setText(" ");
        addressinfo.setText(" ");
        phonenoinfo.setText(" ");
        cmbDept.setSelectedIndex(0);
        //txtid.setText(" ");
        

        }catch (Exception e) {
            JOptionPane.showMessageDialog(this," ");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void cmbDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeptActionPerformed
        // TODO add your handling code here:
        cmbDept.addItem("CSE");
        cmbDept.addItem("ECE");
        cmbDept.addItem("EEE");
        cmbDept.addItem("MECH");
        
    }//GEN-LAST:event_cmbDeptActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:try {
        String name = nameinfo.getText().trim();
        String address =addressinfo.getText().trim();
        String phoneno = phonenoinfo.getText().trim();
        String department = cmbDept.getSelectedItem().toString();

        try{ 
        Connection con = DBConnection.getConnection();

        String sql = "Update studentdata SET name =?,address=?,phoneno=?,department=? WHERE id =?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1,nameinfo.getText());
        ps.setString(2,addressinfo.getText());
        ps.setString(3,phonenoinfo.getText());
        ps.setString(4,cmbDept.getSelectedItem().toString());
       // ps.setInt(5,Integer.parseInt(txtid.getText()));
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successful!");
        ps.close();
        con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int confirm =   JOptionPane.showConfirmDialog(this, "Delete Studentdata?");
        if(confirm==0){
            try{
                Connection con = DBConnection.getConnection();
                String sql= "Delete from studentdata WHERE id =?";
                PreparedStatement ps = con.prepareStatement(sql);
                //ps.setInt(1,Integer.parseInt(txtid.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted Successfully!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
                
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrActionPerformed
        // TODO add your handling code here:
        nameinfo.setText(" ");
        addressinfo.setText(" ");
        phonenoinfo.setText(" ");
        cmbDept.setSelectedIndex(0);
       // txtid.setText(" ");
        
    }//GEN-LAST:event_btnclrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demoinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demoinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demoinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demoinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new demoinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressinfo;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnclr;
    private javax.swing.JComboBox cmbDept;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jaddress;
    private javax.swing.JLabel jdepartment;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jphoneno;
    private javax.swing.JLabel jtitle;
    private javax.swing.JTextField nameinfo;
    private javax.swing.JTextField phonenoinfo;
    // End of variables declaration//GEN-END:variables
}
