/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myjavaapplication;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
  
/**
 *
 * @author MAXPRO
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;



public class demosignup extends javax.swing.JFrame {
    public demosignup() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtname = new javax.swing.JPanel();
        SignupPage = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jbtnnewsignup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jnewlogin = new javax.swing.JButton();
        newpass = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtname.setBackground(new java.awt.Color(255, 204, 204));

        SignupPage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SignupPage.setText("Sign up ");

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setText("Full Name");

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setText("Email");

        jtxtemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemailActionPerformed(evt);
            }
        });

        jpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpassword.setText("Password");

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbtnnewsignup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnnewsignup.setText("Sign up");
        jbtnnewsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnewsignupActionPerformed(evt);
            }
        });

        jLabel5.setText("I've an account");

        jnewlogin.setText("login");
        jnewlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewloginActionPerformed(evt);
            }
        });

        newpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newpass.setText("Confirm Password");

        txtConfirmPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout txtnameLayout = new javax.swing.GroupLayout(txtname);
        txtname.setLayout(txtnameLayout);
        txtnameLayout.setHorizontalGroup(
            txtnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtnameLayout.createSequentialGroup()
                .addGroup(txtnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtnameLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(SignupPage))
                    .addGroup(txtnameLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(txtnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newpass)
                            .addGroup(txtnameLayout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jbtnnewsignup))
                            .addGroup(txtnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtConfirmPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtnameLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jnewlogin))
                                .addComponent(jpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtusername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtemail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        txtnameLayout.setVerticalGroup(
            txtnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtnameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(SignupPage)
                .addGap(18, 18, 18)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnnewsignup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jnewlogin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void jbtnnewsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnewsignupActionPerformed
        // TODO add your handling code here:
        
        String username = txtusername.getText().trim();
        String email =jtxtemail.getText().trim();
        String password = String.valueOf(txtpassword.getText());
        String confirm = String.valueOf(txtConfirmPass.getText());
        
        if(username.isEmpty()|| email.isEmpty()|| password.isEmpty() ||confirm.isEmpty() ){
            JOptionPane.showMessageDialog(this,"All fields are required");
            return;
        }
        if (password.equals(confirm)){
            JOptionPane.showMessageDialog(this, "Registration Successful");
            JOptionPane.showMessageDialog(this, "Signup Successful and move to Homepage");
            demohomepage home = new demohomepage();
            home.setVisible(true);
            this.dispose();  
            
       }else{
            JOptionPane.showMessageDialog(this, "Pasword do not match");
            JOptionPane.showMessageDialog(this, "Signup Error!");
            return;
       }
        try {
          
        Connection con = DBConnection.getConnection();

        String sql = "INSERT INTO users(username,email,password) VALUES(?,?,?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, username);
        ps.setString(2, email);
        ps.setString(3,password);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Signup Successful!");
      //  new demologin().setVisible(true);
        //this.dispose();

        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Username already exists");
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtnnewsignupActionPerformed

    private void jtxtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtemailActionPerformed

    private void jnewloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewloginActionPerformed
        // TODO add your handling code here:
    demologin lp = new demologin();
    new demologin().setVisible(true);
    this.dispose();
        
        
    }//GEN-LAST:event_jnewloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demosignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demosignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demosignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demosignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demosignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignupPage;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnnewsignup;
    private javax.swing.JButton jnewlogin;
    private javax.swing.JLabel jpassword;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JLabel newpass;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JPanel txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
